services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: qa-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orm-dev
    networks:
      - default_network


networks:
  default_network:
    name: default_network
